name: Marketing Automation Lint

on:
  push:
    paths:
      - 'autogen/seo_audit.py'
      - 'autogen/content_strategy.py'
      - 'autogen/marketing_automation.py'
      - '.github/workflows/marketing-automation-lint.yml'
  pull_request:
    paths:
      - 'autogen/seo_audit.py'
      - 'autogen/content_strategy.py'
      - 'autogen/marketing_automation.py'
      - '.github/workflows/marketing-automation-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black mypy types-all
        
    - name: Run black
      run: |
        black --check autogen/seo_audit.py autogen/content_strategy.py autogen/marketing_automation.py
        
    - name: Run ruff
      run: |
        ruff check autogen/seo_audit.py autogen/content_strategy.py autogen/marketing_automation.py
        
    - name: Run mypy
      run: |
        mypy --strict autogen/seo_audit.py autogen/content_strategy.py autogen/marketing_automation.py
