name: Marketing Automation Documentation

on:
  push:
    paths:
      - 'docs/marketing_automation.md'
      - '.github/workflows/marketing-automation-docs.yml'
  pull_request:
    paths:
      - 'docs/marketing_automation.md'
      - '.github/workflows/marketing-automation-docs.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material
        
    - name: Check documentation links
      run: |
        mkdocs build --strict
        
    - name: Deploy documentation
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        mkdocs gh-deploy --force
